Repository SWATEngineering/Docs, pull requests merged in 2023-12, with the labels that each got.

#100 stesura verbale interno 1-12
  src/2_RTB/PianoDiQualifica/content.typ
  src/2_RTB/VerbaliInterni/VerbaleInterno_011223/assets/fonts/IBMPlexSans-Bold.ttf
  src/2_RTB/VerbaliInterni/VerbaleInterno_011223/assets/fonts/IBMPlexSans-BoldItalic.ttf
  src/2_RTB/VerbaliInterni/VerbaleInterno_011223/assets/fonts/IBMPlexSans-Italic.ttf
  src/2_RTB/VerbaliInterni/VerbaleInterno_011223/assets/fonts/IBMPlexSans-Light.ttf
  src/2_RTB/VerbaliInterni/VerbaleInterno_011223/assets/fonts/IBMPlexSans-LightItalic.ttf
  src/2_RTB/VerbaliInterni/VerbaleInterno_011223/assets/fonts/IBMPlexSans-Medium.ttf
  src/2_RTB/VerbaliInterni/VerbaleInterno_011223/assets/fonts/IBMPlexSans-MediumItalic.ttf
  src/2_RTB/VerbaliInterni/VerbaleInterno_011223/assets/fonts/IBMPlexSans-Regular.ttf
  src/2_RTB/VerbaliInterni/VerbaleInterno_011223/assets/swat_logo.png
  src/2_RTB/VerbaliInterni/VerbaleInterno_011223/assets/swat_logo_short.png
  src/2_RTB/VerbaliInterni/VerbaleInterno_011223/assets/unipd_logo.png
  src/2_RTB/VerbaliInterni/VerbaleInterno_011223/changelog.csv
  src/2_RTB/VerbaliInterni/VerbaleInterno_011223/changelog.typ
  src/2_RTB/VerbaliInterni/VerbaleInterno_011223/content.typ
  src/2_RTB/VerbaliInterni/VerbaleInterno_011223/functions.typ
  src/2_RTB/VerbaliInterni/VerbaleInterno_011223/main.typ
  src/2_RTB/VerbaliInterni/VerbaleInterno_011223/meta.typ
  src/2_RTB/VerbaliInterni/VerbaleInterno_011223/participants.csv
Labels: Team Docs

#130 sistemazione versionamento PdP
  src/2_RTB/PianoDiProgetto/changelog.csv
  src/2_RTB/VerbaliInterni/VerbaleInterno_011223/content.typ
Labels: Team Docs

#127 verbale interno 08/12
  src/2_RTB/VerbaliInterni/VerbaleInterno_081223/assets/fonts/IBMPlexSans-Bold.ttf
  src/2_RTB/VerbaliInterni/VerbaleInterno_081223/assets/fonts/IBMPlexSans-BoldItalic.ttf
  src/2_RTB/VerbaliInterni/VerbaleInterno_081223/assets/fonts/IBMPlexSans-Italic.ttf
  src/2_RTB/VerbaliInterni/VerbaleInterno_081223/assets/fonts/IBMPlexSans-Light.ttf
  src/2_RTB/VerbaliInterni/VerbaleInterno_081223/assets/fonts/IBMPlexSans-LightItalic.ttf
  src/2_RTB/VerbaliInterni/VerbaleInterno_081223/assets/fonts/IBMPlexSans-Medium.ttf
  src/2_RTB/VerbaliInterni/VerbaleInterno_081223/assets/fonts/IBMPlexSans-MediumItalic.ttf
  src/2_RTB/VerbaliInterni/VerbaleInterno_081223/assets/fonts/IBMPlexSans-Regular.ttf
  src/2_RTB/VerbaliInterni/VerbaleInterno_081223/assets/swat_logo.png
  src/2_RTB/VerbaliInterni/VerbaleInterno_081223/assets/swat_logo_short.png
  src/2_RTB/VerbaliInterni/VerbaleInterno_081223/assets/unipd_logo.png
  src/2_RTB/VerbaliInterni/VerbaleInterno_081223/changelog.csv
  src/2_RTB/VerbaliInterni/VerbaleInterno_081223/changelog.typ
  src/2_RTB/VerbaliInterni/VerbaleInterno_081223/content.typ
  src/2_RTB/VerbaliInterni/VerbaleInterno_081223/functions.typ
  src/2_RTB/VerbaliInterni/VerbaleInterno_081223/main.typ
  src/2_RTB/VerbaliInterni/VerbaleInterno_081223/meta.typ
  src/2_RTB/VerbaliInterni/VerbaleInterno_081223/participants.csv
Labels: Team Docs

#143 119 corretto diagramma gantt, con data rtb aggiornata
  src/2_RTB/PianoDiProgetto/assets/DiagrammiGantt/DiagrammaQuartoSprint.png
Labels: Team Docs

#146 117 pdp pianificazione 15 16 sprint
  src/2_RTB/PianoDiProgetto/assets/DiagrammiGantt/DiagrammaQuattordicesimoSprint.png
  src/2_RTB/PianoDiProgetto/assets/DiagrammiGantt/DiagrammaQuindicesimoSprint.png
  src/2_RTB/PianoDiProgetto/assets/DiagrammiGantt/DiagrammaSedicesimoSprint.png
  src/2_RTB/PianoDiProgetto/sections/AnalisiDeiRischi.typ
  src/2_RTB/PianoDiProgetto/sections/Pianificazione.typ
  src/2_RTB/PianoDiProgetto/sections/PianificazioneSprint/QuattordicesimoSprint.typ
  src/2_RTB/PianoDiProgetto/sections/PianificazioneSprint/QuindicesimoSprint.typ
  src/2_RTB/PianoDiProgetto/sections/PianificazioneSprint/SedicesimoSprint.typ
  src/2_RTB/PianoDiProgetto/sections/PianificazioneSprint/TredicesimoSprint.typ
Labels: Team Docs

#125 101 restructuring adr from the ground up
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC1.1_Visualizzazione-posizione-sensori-su-mappa.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC1.2_Visualizzazione-tabella-sensori.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC10_Inserimento-dati-temperatura.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC11_Inserimento-dati-umidità.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC12_Inserimento-dati-velocità-e-direzione-del-vento.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC13_Inserimento-dati-precipitazioni.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC14_Inserimento-dati-inquinamento-dell-aria.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC15_Inserimento-dati-livello-bacini-idrici.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC16_Inserimento-dati-disponibilità-parcheggi.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC17_Inserimento-dati-colonne-di-ricarica.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC18_Inserimento-dati-biciclette-elettriche.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC19_Inserimento-dati-riempimento-zone-ecologiche.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC1_Visualizzazione-panoramica-generale-sensori.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC2.10_Visualizzazione-pannello-temperatura-media.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC2.11_Visualizzazione-pannello-inquinamento-dell-aria-massimo.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC2.1_Visualizzazione-pannello-dati-ambientali.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC2.2_Visualizzazion-pannello-time-series-per-temperatura.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC2.3_Visualizzazione-pannello-time-series-umidità.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC2.4_Visualizzazione-grafico-a-mappa-velocità-e-direzione-del-vento.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC2.5_Visualizzazione-pannello-time-series-per-precipitazioni.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC2.6_Visualizzazione-pannello-precipitazioni-medie.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC2.7_Visualizzazione-pannello-time-series-per-inquinamento-dell-aria.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC2.8_Visualizzazione-pannello-inquinamento-dell-aria-medio.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC2.9_Visualizzazione-pannello-time-series-per-livello-dei-bacini-idrici.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC20_Inserimento-dati-congestione-stradale.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC2_Visualizzazione-dati-ambientali.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC3.1_Visualizzazione-pannello-dati-urbanistici.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC3.2_Visualizzazione-grafico-a-mappa-disponibilità-dei-parcheggi.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC3.3_Visualizzazione-posizione-e-stato-colonne-ricarica.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC3.4_Visualizzazione-grafico-a-mappa-intensità-traffico.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC3.5_Visualizzazione-posizione-real-time-delle-biciclette-elettriche-e-relativa-percentuale-batteria.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC3.6_Visualizzazione-indicatore-percentuale-su-mappa-riempimento-zone-rifiuti.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC3_Visualizzazione-dati-urbanistici.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC4_Visualizzazione-dati-anomali-rilevati.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC5_Visualizzazione-allerte-superamento-soglie.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC6.1_Filtro-sotto-insieme-di-sensori-su-grafici-time-series.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC6.2_Filtro-per-tipologia-sensore-su-tabella.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC6.3_Filtro-per-nome-sensore-su-tabella.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC6.4_Filtro-per-intervallo-temporale.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC6_Applicazione-filtri.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC7_Ordinamento-pannelli-tabellari.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UML/UC8_Modifica-layout-pannelli.png
  src/2_RTB/AnalisiDeiRequisiti/assets/UtenteUC.png
  src/2_RTB/AnalisiDeiRequisiti/assets/attori.png
  src/2_RTB/AnalisiDeiRequisiti/assets/uc1.png
  src/2_RTB/AnalisiDeiRequisiti/assets/uc2.png
  src/2_RTB/AnalisiDeiRequisiti/assets/uc3.png
  src/2_RTB/AnalisiDeiRequisiti/assets/uc4.png
  src/2_RTB/AnalisiDeiRequisiti/assets/uc7.png
  src/2_RTB/AnalisiDeiRequisiti/changelog.csv
  src/2_RTB/AnalisiDeiRequisiti/content.typ
  src/2_RTB/AnalisiDeiRequisiti/diagrammacasiduso.puml
  src/2_RTB/AnalisiDeiRequisiti/functions.typ
  src/2_RTB/Glossario/changelog.csv
  src/2_RTB/Glossario/terms.csv
Labels: Team Docs

#147 Aggiunto automatismo per ripulire il glossario e indicizzarlo per letttere
  src/2_RTB/Glossario/changelog.csv
  src/2_RTB/Glossario/content.typ
Labels: Team Docs, Amministratore

#152 Stesura verbale interno 15-12-23
  src/2_RTB/VerbaliInterni/VerbaleInterno_151223/assets/fonts/IBMPlexSans-Bold.ttf
  src/2_RTB/VerbaliInterni/VerbaleInterno_151223/assets/fonts/IBMPlexSans-BoldItalic.ttf
  src/2_RTB/VerbaliInterni/VerbaleInterno_151223/assets/fonts/IBMPlexSans-Italic.ttf
  src/2_RTB/VerbaliInterni/VerbaleInterno_151223/assets/fonts/IBMPlexSans-Light.ttf
  src/2_RTB/VerbaliInterni/VerbaleInterno_151223/assets/fonts/IBMPlexSans-LightItalic.ttf
  src/2_RTB/VerbaliInterni/VerbaleInterno_151223/assets/fonts/IBMPlexSans-Medium.ttf
  src/2_RTB/VerbaliInterni/VerbaleInterno_151223/assets/fonts/IBMPlexSans-MediumItalic.ttf
  src/2_RTB/VerbaliInterni/VerbaleInterno_151223/assets/fonts/IBMPlexSans-Regular.ttf
  src/2_RTB/VerbaliInterni/VerbaleInterno_151223/assets/swat_logo.png
  src/2_RTB/VerbaliInterni/VerbaleInterno_151223/assets/swat_logo_short.png
  src/2_RTB/VerbaliInterni/VerbaleInterno_151223/assets/unipd_logo.png
  src/2_RTB/VerbaliInterni/VerbaleInterno_151223/changelog.csv
  src/2_RTB/VerbaliInterni/VerbaleInterno_151223/changelog.typ
  src/2_RTB/VerbaliInterni/VerbaleInterno_151223/content.typ
  src/2_RTB/VerbaliInterni/VerbaleInterno_151223/functions.typ
  src/2_RTB/VerbaliInterni/VerbaleInterno_151223/main.typ
  src/2_RTB/VerbaliInterni/VerbaleInterno_151223/meta.typ
  src/2_RTB/VerbaliInterni/VerbaleInterno_151223/participants.csv
Labels: Responsabile

#133 128 cruscotto metriche PdQ
  src/2_RTB/PianoDiQualifica/assets/valutazione-metriche/AC_ETC.png
  src/2_RTB/PianoDiQualifica/assets/valutazione-metriche/BV_SV.png
  src/2_RTB/PianoDiQualifica/assets/valutazione-metriche/CO.png
  src/2_RTB/PianoDiQualifica/assets/valutazione-metriche/EAC.png
  src/2_RTB/PianoDiQualifica/assets/valutazione-metriche/EV_PV.png
  src/2_RTB/PianoDiQualifica/assets/valutazione-metriche/IG.png
  src/2_RTB/PianoDiQualifica/changelog.csv
  src/2_RTB/PianoDiQualifica/content.typ
Labels: Team Docs

#166 137 controllo adr
  src/2_RTB/AnalisiDeiRequisiti/changelog.csv
  src/2_RTB/AnalisiDeiRequisiti/content.typ
  src/2_RTB/Glossario/terms.csv
Labels: Analista

#171 156 - aggiunto comando mancante nelle istruzioni
  src/2_RTB/PianoDiProgetto/timeresource_sheets_downloader.py
Labels: Amministratore
